name: CI â€“ Reverse Proxy Lab

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y tree
          tree -L 3

      - name: Check .env.example exists
        run: |
          test -f .env.example

      - name: Validate docker-compose
        run: |
          docker compose config

      - name: Validate Kubernetes manifests
        uses: instrumenta/kubeval-action@master
        with:
          files: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/ingress.yaml
